// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteState } from "./NoteState";

export type ColorchordState = { notes: Array<NoteState>, folded: Array<number>, };
