// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";
import type { ParamValue } from "./ParamValue";

export type PatternParam = { name: string, kind: ParamKind, value: ParamValue, };
