// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorchordState } from "./ColorchordState";

/**
 * TypeScript-friendly description of the world state (for .d.ts generation).
 */
export type WorldState = { framerate: number, index: number, delta: number, phase: number, bar: number, bpm: number, colorchord: ColorchordState, };
