[package]
name = "cubeclient"
version = "0.1.0"
authors = ["coral <jonas@jonasbengtson.se>"]
edition = "2024"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1.50", features = ["full"] }


[target.'cfg(target_arch = "arm")'.dependencies]
blinkt = {git = "https://github.com/coral/blinkt.git"}
rppal = "0.12.0"
